[theme]
primaryColor="#2214c7"
backgroundColor="#ffffff"
secondaryBackgroundColor="#e8eef9"
textColor="#000000"
font="sans serif"
[connections.postgresql]
dialect = "postgresql"
host = "stoic-duke-15588.7tt.aws-us-east-1.cockroachlabs.cloud"
port = "26257"
database = "defaultdb"
username = "supreme"
password = "Z0lGvbB_Hs7Lvt104K2ZFw"
sslmode = "verify-full"
