[connections.postgresql]
host = "stoic-duke-15588.7tt.aws-us-east-1.cockroachlabs.cloud"
port = "26257"
database = "defaultdb"
username = "supreme"
password = "Z0lGvbB_Hs7Lvt104K2ZFw"
sslmode = "verify-full"
