[connections.postgresql.create_engine_kwargs.connect_args]
DB_HOST = "stoic-duke-15588.7tt.aws-us-east-1.cockroachlabs.cloud"
DB_PORT = "26257"
DB_DATABASE = "defaultdb"
DB_USER = "supreme"
DB_PASSWORD = "Z0lGvbB_Hs7Lvt104K2ZFw"
DB_SSLMODE = "verify-full"
